branch-defaults:
  default:
    environment: intro
    group_suffix: null
global:
  application_name: intro
  branch: null
  default_ec2_keyname: fan
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
